native bool:EnableStuntBonusForAll(bool:enable);

native bool:EnableStuntBonusForPlayer(Player:player, bool:enable);

native bool:GetStuntBonusForPlayer(Player:player);

native bool:SetGravity(Float:gravity);

native bool:SetPlayerGravity(Player:player, Float:gravity);

native Float:GetPlayerGravity(Player:player);

native bool:SetWeather(weather);

native bool:SetPlayerWeather(Player:player, weather);

native GetPlayerWeather(Player:player);

native bool:EnableZoneNames(bool:enable);

native bool:AllowInteriorWeapons(bool:enable);

native bool:SetDeathDropAmount(amount);

native bool:EnableTirePopping(bool:enable);

native bool:LimitGlobalChatRadius(Float:range);

