#if defined _inc_map
	#endinput
#endif
#define _inc_map

#define MAPICON_LOCAL                          (0) // displays in the player's local area
#define MAPICON_GLOBAL                         (1) // displays always
#define MAPICON_LOCAL_CHECKPOINT               (2) // displays in the player's local area and has a checkpoint marker
#define MAPICON_GLOBAL_CHECKPOINT              (3) // displays always and has a checkpoint marker
